server:
  port: 9000
  error:
    path: /error
    whitelabel:
      enabled: false

spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
  datasource:
    password: ${DB_PASSWORD}
    username: ${DB_USER}
    url: jdbc:postgresql://localhost:5432/db