CREATE TABLE IF NOT EXISTS GRUPPE(
    ID UUID PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL,
    OFFEN BOOLEAN DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS AUSGABE(
    ID SERIAL PRIMARY KEY,
    GRUPPENID UUID NOT NULL,
    NAME VARCHAR(50) NOT NULL,
    BESCHREIBUNG VARCHAR(200),
    BETRAG NUMERIC(15,2) NOT NULL,
    BEZAHLT_VON VARCHAR(50) NOT NULL,
    FOREIGN KEY (GRUPPENID) REFERENCES GRUPPE(ID)
);

CREATE TABLE IF NOT EXISTS BETEILIGT
(
    AUSGABEID    INT         NOT NULL,
    GITHUBHANDLE VARCHAR(50) NOT NULL,
    FOREIGN KEY (AUSGABEID) REFERENCES AUSGABE (ID)
);

CREATE TABLE IF NOT EXISTS MITGLIED(
    GRUPPENID UUID NOT NULL,
    GITHUBHANDLE VARCHAR(50) NOT NULL,
    FOREIGN KEY (GRUPPENID) REFERENCES GRUPPE(ID)
);


